stages:
  - npm
  - docker

# #######################
#          npm          #
# #######################

npm-build:
  stage: npm
  tags:
    - linux
    - docker
  image: docker.io/library/node:24
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - pnpm install
    - pnpm run build
  artifacts:
    name: dist
    paths:
      - ./dist/

# #######################
#         Docker        #
# #######################

docker-build:
  stage: docker
  tags:
    - linux
    - docker
    - amd64
    - mpc
  image: docker.io/library/docker:cli
  services:
    - name: docker.io/library/docker:dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ''
    CONTAINER_IMAGE_NAME: cdn-ips
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin docker.io
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    # 解包并构建
    - docker build --pull -t "$CONTAINER_IMAGE_NAME:$CI_COMMIT_TAG" .
    - docker tag $CONTAINER_IMAGE_NAME:$CI_COMMIT_TAG $CONTAINER_IMAGE_NAME:latest
    # 为 Docker Hub 打远程仓库标签
    - docker tag $CONTAINER_IMAGE_NAME:$CI_COMMIT_TAG docker.io/$DOCKERHUB_USER/$CONTAINER_IMAGE_NAME:$CI_COMMIT_TAG
    - docker tag $CONTAINER_IMAGE_NAME:latest docker.io/$DOCKERHUB_USER/$CONTAINER_IMAGE_NAME:latest
    # 为私有仓库打远程仓库标签
    - docker tag $CONTAINER_IMAGE_NAME:$CI_COMMIT_TAG $CI_REGISTRY/xiaoxi/$CONTAINER_IMAGE_NAME:$CI_COMMIT_TAG
    - docker tag $CONTAINER_IMAGE_NAME:latest $CI_REGISTRY/xiaoxi/$CONTAINER_IMAGE_NAME:latest
    # 推送 Docker Hub
    - docker push docker.io/$DOCKERHUB_USER/$CONTAINER_IMAGE_NAME:$CI_COMMIT_TAG
    - docker push docker.io/$DOCKERHUB_USER/$CONTAINER_IMAGE_NAME:latest
    # 推送私有仓库
    - docker push $CI_REGISTRY/xiaoxi/$CONTAINER_IMAGE_NAME:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY/xiaoxi/$CONTAINER_IMAGE_NAME:latest
